---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-7-0-x64
  driver:
    name: digitalocean

- name: ubuntu-14-04-x64
  driver:
    name: digitalocean

- name: ubuntu-16-04-x64
  driver:
    name: digitalocean

verifier:
  name: inspec
  sudo: true
  format: doc

transport:
  ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[demo_cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
